//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCH_TF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacion_ruta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asignacion_ruta()
        {
            this.creacion_usuario = new HashSet<creacion_usuario>();
        }
    
        public int id_proceso_asignacion { get; set; }
        public string cod_ruta { get; set; }
        public int empleado { get; set; }
        public int cod_registro { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual proceso_registro proceso_registro { get; set; }
        public virtual empleado empleado1 { get; set; }
        public virtual ruta_ciudad ruta_ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<creacion_usuario> creacion_usuario { get; set; }
    }
}
