//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCH_TF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creacion_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public creacion_usuario()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public int id_proceso_usuario { get; set; }
        public int cod_registro { get; set; }
        public int ruta_asignada { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual asignacion_ruta asignacion_ruta { get; set; }
        public virtual proceso_registro proceso_registro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
