//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCH_TF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado()
        {
            this.asignacion_ruta = new HashSet<asignacion_ruta>();
            this.proceso_formularios = new HashSet<proceso_formularios>();
            this.proceso_registro = new HashSet<proceso_registro>();
        }
    
        public int id_empleado { get; set; }
        public string contraseña { get; set; }
        public string cedula_empleado { get; set; }
        public string nombres_empleado { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public int tipo_empleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignacion_ruta> asignacion_ruta { get; set; }
        public virtual tipo_empleado tipo_empleado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proceso_formularios> proceso_formularios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proceso_registro> proceso_registro { get; set; }
    }
}
