//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCH_TF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proceso_formularios
    {
        public int id_form { get; set; }
        public int empleado { get; set; }
        public int estado_proceso { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual empleado empleado1 { get; set; }
        public virtual estado_formulario estado_formulario { get; set; }
        public virtual formularios formularios { get; set; }
    }
}
