//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCH_TF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proceso_registro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proceso_registro()
        {
            this.asignacion_ruta = new HashSet<asignacion_ruta>();
            this.creacion_usuario = new HashSet<creacion_usuario>();
        }
    
        public int id_proceso { get; set; }
        public int id_empleado { get; set; }
        public int id_registro { get; set; }
        public int id_estado { get; set; }
        public System.DateTime fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignacion_ruta> asignacion_ruta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<creacion_usuario> creacion_usuario { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual estado_formulario estado_formulario { get; set; }
        public virtual form_registro form_registro { get; set; }
    }
}
