//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCH_TF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class repartidor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public repartidor()
        {
            this.ruta_ciudad = new HashSet<ruta_ciudad>();
        }
    
        public int id_repartidor { get; set; }
        public string cedula_repartidor { get; set; }
        public string nombres_repartidor { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string coche { get; set; }
        public int ing_asignado { get; set; }
    
        public virtual coche_repartidor coche_repartidor { get; set; }
        public virtual ing_hidrocarburos ing_hidrocarburos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ruta_ciudad> ruta_ciudad { get; set; }
    }
}
