//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCH_TF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ruta_ciudad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ruta_ciudad()
        {
            this.asignacion_ruta = new HashSet<asignacion_ruta>();
        }
    
        public string cod_ruta { get; set; }
        public int repartidor { get; set; }
        public string nombre_ruta { get; set; }
        public string zona_ciudad { get; set; }
        public string direccion_limites { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignacion_ruta> asignacion_ruta { get; set; }
        public virtual repartidor repartidor1 { get; set; }
        public virtual zona_ciudad zona_ciudad1 { get; set; }
    }
}
